keyword_normalization:
  "banh chung Tet": "bánh chưng"
  "Buffalo fighting festival": "lễ hội chọi trâu"
  "Gióng festival": "lễ hội Gióng"
  "Kate festival": "lễ hội Katê"
  "MMA Vietnam": "MMA Việt Nam"
  "Tet Nguyên Đan Việt Nam": "Tết Nguyên Đán"
  "Trung thu Việt Nam": "Tết Trung thu"
  "Valentine Việt Nam": "Valentine"
  "Vietnamese zither": "đàn tranh"
  "Vu Lan festival": "Lễ Vu Lan"
  "Văn Mieu Quốc Tử Giam": "Văn Miếu Quốc Tử Giám"
  "ao choang lemur": "áo choàng"
  "ban no": "bán nỏ"
  "banh bao": "bánh bao"
  "banh chay": "bánh chay"
  "banh căn Phan Thiet": "bánh căn"
  "banh day": "bánh dày"
  "banh flan": "bánh flan"
  "banh gio": "bánh giò"
  "banh in": "bánh in"
  "banh it": "bánh ít"
  "banh pia": "bánh pía"
  "banh ran": "bánh rán"
  "banh trang nuớng": "bánh tráng nướng"
  "biệt thự Phap": "biệt thự Pháp"
  "boxing Vietnam": "boxing Việt Nam"
  "buu điện Sai Gòn": "bưu điện Sài Gòn"
  "bóng ban Việt Nam": "bóng bàn"
  "bóng chuyen bai biển Việt Nam": "bóng chuyền bãi biển"
  "bóng rổ đuong phố Việt Nam": "bóng rổ đường phố"
  "bóng đa phong trao Việt Nam": "bóng đá phong trào"
  "bơi loi Việt Nam": "bơi lội"
  "ca phê phin": "cà phê phin"
  "chao ca": "cháo cá"
  "chao lòng": "cháo lòng"
  "chè buởi": "chè bưởi"
  "chùa Ba Đen": "chùa Bà Đen"
  "chùa Cao Đai": "chùa Cao Đài"
  "chùa Jade Emperor": "chùa Ngọc Hoàng"
  "chùa Tam Chúc": "chùa Tam Chúc"
  "chùa Trấn Quốc": "chùa Trấn Quốc"
  "chùa Việt Nam": "chùa Việt Nam"
  "chả ca La Vọng": "chả cá Lã Vọng"
  "chả que Hung Yên": "chả que Hưng Yên"
  "co tuớng Việt Nam": "cờ tướng Việt Nam"
  "cot co Ha Noi": "cột cờ Hà Nội"
  "cung An Định": "Cung An Định"
  "cơm âm phu Hue": "cơm âm phủ Huế"
  "cầu Long Biên": "cầu Long Biên"
  "cầu Nhật Bản Hoi An": "cầu Nhật Bản Hội An"
  "cầu Thê Húc": "cầu Thê Húc"
  "cầu lông Việt Nam": "cầu lông Việt Nam"
  "cầu mây Việt Nam": "cầu mây Việt Nam"
  "cồng chiêng": "cồng chiêng"
  "cổng thanh Ha Noi": "cổng thành Hà Nội"
  "cử tạ Việt Nam": "cử tạ Việt Nam"
  "dan co": "dàn cờ"
  "dinh Đoc Lập": "Dinh Độc Lập"
  "diving Vietnam": "diving Việt Nam"
  "dây chuyen bạc": "dây chuyền bạc"
  "festival Hue": "lễ hội Huế"
  "gymnastics Vietnam": "thể dục dụng cụ Việt Nam"
  "hoang thanh Thăng Long": "Hoàng thành Thăng Long"
  "ken bau Vietnam": "kèn bầu"
  "khuyên tai dân toc": "khuyên tai dân tộc"
  "khăn piêu Thai": "khăn piêu Thái"
  "khăn ran Nam Bo": "khăn rằn Nam Bộ"
  "khăn đóng Hue": "khăn đóng Huế"
  "kickboxing Vietnam": "kickboxing Việt Nam"
  "kien trúc Gothic": "kiến trúc Gothic"
  "kien trúc Hue": "kiến trúc Huế"
  "kim khi": "kim khí"
  "kinh thanh Hue": "Kinh thành Huế"
  "kèn la": "kèn lá"
  "kẹo dua Ben Tre": "kẹo dừa Bến Tre"
  "le 20 11": "Lễ 20-11"
  "le 8 3": "Lễ 8-3"
  "le Quốc khanh": "Lễ Quốc khánh"
  "le gio tổ Hùng Vuơng": "lễ giỗ Tổ Hùng Vương"
  "le hoi Chaul Chnam Thmey": "lễ hội Chaul Chnam Thmey"
  "le hoi Dôn Ta": "lễ hội Dôn Ta"
  "le hoi Ghe Ngo": "lễ hội Ghe Ngo"
  "le hoi Nang Hai": "lễ hội Nang Hai"
  "le hoi Roóng Poọc": "lễ hội Roóng Poọc"
  "le hoi Sene Dolta": "lễ hội Sene Dolta"
  "le hoi banh chung": "lễ hội bánh chưng"
  "le hoi café": "lễ hội cà phê"
  "le hoi chùa Huơng": "lễ hội chùa Hương"
  "le hoi cúng ơn": "lễ hội cúng ơn"
  "le hoi cầu ngu": "lễ hội cầu ngư"
  "le hoi hai lúa": "lễ hội hai lúa"
  "le hoi harvest": "lễ hội thu hoạch"
  "le hoi hoa anh đao": "lễ hội hoa anh đào"
  "le hoi hoa ban": "lễ hội hoa ban"
  "le hoi lang": "lễ hội làng"
  "le hoi múa lân": "lễ hội múa lân"
  "le hoi nuớc": "lễ hội nước"
  "le hoi ném còn": "lễ hội ném còn"
  "le hoi phao hoa": "lễ hội pháo hoa"
  "le hoi tinh yêu": "lễ hội tình yêu"
  "le hoi Óc Om Bóc": "lễ hội Óc Om Bóc"
  "le hoi đen Hùng": "lễ hội Đền Hùng"
  "le hoi đua thuyen": "lễ hội đua thuyền"
  "lân su rồng thi đấu": "lân sư rồng thi đấu"
  "lăng Hồ Chi Minh": "lăng Hồ Chí Minh"
  "lăng Tu Đuc": "lăng Tự Đức"
  "ma lai festival": "lễ hội Malaysia"
  "mam ruốc": "mắm ruốc"
  "mam tôm": "mắm tôm"
  "marathon Vietnam": "marathon Việt Nam"
  "moon lute": "đàn nguyệt"
  "musical Vietnam": "nhạc Việt Nam"
  "mõ go": "mõ gỗ"
  "nem chua": "nem chua"
  "nem nuớng": "nem nướng"
  "nha Bac Hồ": "Nhà Bác Hồ"
  "nha dai Ê Đê": "nhà dài Ê-Đê"
  "nha hat Lớn Ha Noi": "Nhà hát Lớn Hà Nội"
  "nha san H'Mông": "nhà sàn H'Mông"
  "nha san Tây Bac": "nhà sàn Tây Bắc"
  "nha tho Đuc Ba": "nhà thờ Đức Bà"
  "nha truyen thống mien Tây": "nhà truyền thống miền Tây"
  "nha vuon Hue": "nhà vườn Huế"
  "nón bai thơ": "nón bài thơ"
  "nón quai thao": "nón quai thao"
  "phố cổ Ha Noi": "phố cổ Hà Nội"
  "quyen anh Việt Nam": "quyền anh Việt Nam"
  "quảng truong Ba Đinh": "quảng trường Ba Đình"
  "ram thang Bảy": "Rằm tháng Bảy"
  "ram thang Giêng": "Rằm tháng Giêng"
  "ruong bậc thang kien trúc": "ruộng bậc thang"
  "sao kèn": "sáo kèn"
  "sao mọi": "sáo mọi"
  "sao pi": "sáo pí"
  "sao trúc": "sáo trúc"
  "sao đieu": "sáo diều"
  "sarong Chăm": "sarong Chăm"
  "taekwondo Việt Nam": "taekwondo Việt Nam"
  "tennis Việt Nam": "tennis Việt Nam"
  "tet Đoan ngọ": "Tết Đoan Ngọ"
  "thai cực quyen Việt Nam": "Thái Cực Quyền Việt Nam"
  "thap Rùa": "tháp Rùa"
  "that lung thổ cẩm": "thắt lưng thổ cẩm"
  "trang phục Giay": "trang phục giày"
  "trang phục La Chi": "trang phục La Chí"
  "trang phục Muong": "trang phục Mường"
  "trang phục Tay": "trang phục Tày"
  "trang phục dân toc": "trang phục dân tộc"
  "trống com": "trống cơm"
  "turban Chăm": "turban Chăm"
  "tuơng ớt": "tương ớt"
  "vay thổ cẩm": "váy thổ cẩm"
  "vòng cổ H'Mông": "vòng cổ H'Mông"
  "võ cổ truyen Việt Nam": "võ cổ truyền Việt Nam"
  "vật cổ truyen Việt Nam": "vật cổ truyền Việt Nam"
  "wrestling Vietnam": "wrestling Việt Nam"
  "yem đao": "yếm đào"
  "đam cuới Việt Nam": "đám cưới"
  "đan K'ni": "đan K'ni"
  "đan T'rung": "đàn T'rưng"
  "đan bầu đoc huyen": "đàn bầu độc huyền"
  "đan nguyệt": "đàn nguyệt"
  "đan nhị": "đàn nhị"
  "đan sen": "đàn sến"
  "đan thập lục": "đàn thập lục"
  "đan ty ba": "đàn tỳ bà"
  "đanh gậy truyen thống": "đánh gậy truyền thống"
  "đen Bạch Ma": "Đền Bạch Mã"
  "đen Hùng": "Đền Hùng"
  "đen Ngọc Sơn": "Đền Ngọc Sơn"
  "đien kinh SEA Games Việt Nam": "điền kinh SEA Games Việt Nam"
  "đinh Bảng": "Đình Bảng"
  "đinh lang Việt Nam": "Đình Làng Việt Nam"
  "đua bò Bảy Núi": "đua bò Bảy Núi"
  "đua thuyen kayak Hạ Long": "đua thuyền kayak Hạ Long"
  "đua xe đạp": "đua xe đạp"
  "đẩy gậy": "đẩy gậy"
  "banh gai": "bánh gai"
  "banh khọt": "bánh khọt"
  "banh đậu xanh": "bánh đậu xanh"
  "canh chua": "canh chua"
  "chiêng đồng": "chiêng đồng"
  "chuông chùa": "chuông chùa"
  "chè Việt Nam": "chè"
  "chả lụa": "chả lụa"
  "chợ Đồng Xuân": "chợ Đồng Xuân"
  "côn nhị khúc": "côn nhị khúc"
  "cầu Cầu": "cầu Cầu"
  "judo Việt Nam": "judo Việt Nam"
  "karatedo Việt Nam": "karatedo Việt Nam"
  "khăn piêu đầu": "khăn piêu đầu"
  "khăn thổ cẩm": "khăn thổ cẩm"
  "kèn bầu": "kèn bầu"
  "le hoi Bunpchum": "lễ hội Bunpchum"
  "le hoi chọi trâu": "lễ hội chọi trâu"
  "lăng Khải Định": "lăng Khải Định"
  "lăng Minh Mạng": "lăng Minh Mạng"
  "muay Việt Nam": "muay Việt Nam"
  "nha tho thanh thất": "nhà thờ Thanh Thất"
  "thổ cẩm": "thổ cẩm"
  "trang phục Chăm": "trang phục Chăm"
  "trang phục Cơ Tu": "trang phục Cơ Tu"
  "trang phục Dao": "trang phục Dao"
  "trang phục H'Mông": "trang phục H'Mông"
  "trang phục Khmer": "trang phục Khmer"
  "trang phục Nùng": "trang phục Nùng"
  "trang phục Ê Đê": "trang phục Ê-Đê"
  "trống Việt Nam": "trống Việt Nam"
  "trống chầu": "trống chầu"
  "trống cơm": "trống cơm"
  "trống đồng": "trống đồng"
  "tôm khô": "tôm khô"
  "túi thổ cẩm": "túi thổ cẩm"
  "vòng tay bạc": "vòng tay bạc"
  "vịt quay": "vịt quay"
  "xôi gấc": "xôi gấc"
  "đinh Đen Lu": "Đinh Đen Lu"
  "ao ba ba": "áo bà ba"
  "ao dai Việt Nam": "áo dài"
  "ao dai cach tân": "áo dài cách tân"
  "ao dai cuới": "áo dài cưới"
  "ao dai học sinh": "áo dài học sinh"
  "ao dai nam": "áo dài nam"
  "ao dai trẻ em": "áo dài trẻ em"
  "ao gấm Hue": "áo gấm Huế"
  "ao tu thân": "áo tứ thân"
  "ao yem truyen thống": "áo yếm truyền thống"
  "banh mi Việt Nam": "bánh mì"
  "banh chung gù": "bánh chưng gù"
  "bún bò Hue": "bún bò Huế"
  "bún chả Ha Noi": "bún chả Hà Nội"
  "bún thịt nuớng": "bún thịt nướng"
  "cao lầu Hoi An": "cao lầu Hội An"
  "chùa Bai Đinh": "chùa Bái Đính"
  "chùa Mot Cot": "chùa Một Cột"
  "chùa Ngọc Hoang": "chùa Ngọc Hoàng"
  "cơm tấm Sai Gòn": "cơm tấm Sài Gòn"
  "ga nuớng": "gà nướng"
  "giay go": "giày gỗ"
  "goi cuốn": "gỏi cuốn"
  "nha cổ Hoi An": "nhà cổ Hội An"
  "nha rồng HCMC": "nhà rồng Thành phố Hồ Chí Minh"
  "nón la Việt Nam": "nón lá"
  "mi Quảng": "mì Quảng"
  "nuớc mam Phú Quốc": "nước mắm Phú Quốc"
  "phở Việt Nam": "phở"
  "tet Trung thu": "Tết Trung thu"
  "tet Han thực": "Tết Hàn thực"
  "mut Tet": "mứt Tết"
  "banh bot lọc": "bánh bột lọc"
  "banh cuốn": "bánh cuốn"
  "banh tét": "bánh tét"
  "banh xèo": "bánh xèo"
  "bánh đậu xanh": "bánh đậu xanh"
  "bánh mì Việt Nam": "bánh mì"
  "phu Chu tịch": "Phú Chủ tịch"
  "nón nón la Hue": "nón lá Huế"
  "vovinam biểu dien": "Vovinam biểu diễn"
  "võ Binh Định": "võ Bình Định"
  "võ Tây Sơn": "võ Tây Sơn"
  "đan đay Vietnamese": "đan đay"
  "đan bầu Việt Nam": "đàn bầu"
  "đan ghi ta Việt Nam": "đàn ghi-ta"
  "đan tam thập lục": "đàn tam thập lục"
  "đan tranh": "đàn tranh"
  "đua thuyen rồng Việt Nam": "đua thuyền rồng"
  "đua ghe ngo": "đua ghe ngo"
  "bamboo flute Vietnam": "sáo trúc"
  "Vietnamese zither": "đàn tranh"